stampit-org/stampit

- test/index.html
Update test/index.html to pass validation.
Code checked at:
http://validator.w3.org/
> Update test/index.html to pass validation

- dist/stampit.js
- package.json
- test/index.html
- test/qunit.css
- test/qunit.js
- test/stampit.js
SauceLabs was not reporting "Pass" at times. Easy fix. All it need is the latest `grunt-saucelabs` and the new QUnit. After the upgrades here is what it was and became: [Picture](http://storage6.static.itmages.com/i/15/0107/h_1420621796_3123914_1b69e5cc39.png).
Please, pull the [upgrade_saucelabs](https://github.com/ericelliott/stampit/tree/upgrade_saucelabs) branch and `npm test` to make sure it works for you.
> Upgrade SauceLabs. Make sure it reports Pass on success - upgrade QUnit.

- README.md
- package.json
- stampit.js
> Fix silly merge conflicts

- test/init.js
added test for order init functions are called
added test for stamp and opts.instace match
> init tests

- README.md
A more detailed contributing section should be added in the docs folder later.
See https://github.com/stampit-org/stampit/issues/122
> [#122] Remove bad contributing section

- package.json
> New command `npm run check`, automatically runs on prepublish.

- ADVANCED_EXAMPLES.md
- README.md
- package.json
- src/stampit.js
- test/init.js
- test/promise-init.js
- test/v1-compatibility.js
> Stamps as promised

- README.md
Trying to achieve that sort of a readme: https://github.com/stampit-org/stampit/issues/122#issuecomment-118570103
> Real life example in readme

- docs/API.md
> fix connection typo

- README.md
People are judging a module by it's first code sample. I want to emphasize that composition is the core feature of the stampit.
> First code sample should showcase the essence of factory composition

- README.md
I linked the two broken links to https://vimeo.com/69255635
> Fix "learning about prototypal OO" link

- isComposable.js
- isStamp.js
- src/stampit.js
Based on [#209](https://github.com/stampit-org/stampit/pull/209#issuecomment-222907611)
I am not much of a fan of having source file outside of src folder, but I guess this is best way for greater good.
/cc @ericelliott @koresar
> Export isComposable and isStamp separately

- build/index.js
- package.json
This modification alters how stampit is exported for Node.js.  Currently, if you are not using ES6 modules, you need to do this:
```js
const stampit = require('stampit').default;
const MyStamp = stampit();
```
This PR changes the appropriate dist file(s) so that the following is possible:
```js
const stampit = require('stampit');
const MyStamp = stampit();
```
There's `babel-plugin-add-module-exports`, but that assumes a `es2015-preset` is in use; it's not here.  I couldn't find a suitable Rollup plugin, so I just wrote my own.
Here's some REPL output of how it looks different:
Before:
```js
> require('stampit')
{ compose: [Function: compose],
isComposable: [Function: isObject],
isStamp: [Function: isStamp],
methods: [Function: methods],
properties: [Function: properties],
refs: …
```
> allow easier usage by cjs modules

- docs/API.md
Maybe too long explanation for API listing? Any idea where else to put it?
> Update API.md regarding props and mutability

- src/stampit.js
So, I've noticed that there is a bunch of copy-pasted code.
This change not only makes the code shorter, but also (possibly) faster.
> Code shortening

- README.md
UNPKG would list the available distributable files instead of the node.js/CJS one.
> Warning about Object.assign polyfill

- README.md
Thanks @abhisekp for reporting this
> Fix release links in readme

- src/extract-functions.js
The code courtesy of @abhisekp
> Shorter extractFunctions

- README.md
Otherwise it just shows that the current build is failing.
> Fix Travis-CI badge URL

- README.md
It was just merged moments ago, so it's like got new thing :)
> Proper cndjs badge with version number

- README.md
MOAR BADGES! :)
[![npm](https://img.shields.io/npm/dm/stampit.svg)](https://www.npmjs.com/package/stampit)
> "Downloads per month" badge

- .travis.yml
- package.json
- src/compose.js
- src/isStamp.js
- src/stampit.js
- src/standardise-descriptor.js
- test/benchmark/property-access.js
- test/index.js
* Fix property access perf.
* Fix some JSDoc comments.
* Run CI tests for node v7 too.
* Add benchmarking test, make it run in CI only.
> Obj create perf fix

- .npmignore
@koresar It looks like that you have published your .idea folder in 3.0.5 version :)
> Ignore .idea folder from NPM

- README.md
https://github.com/stampit-org/stampit/issues/273
> fix(readme): Properly document destructuring usage in simplest example

- package.json
> chore(package): update eslint-config-airbnb-base to version 11.0.0

- package.json
- test/benchmark/.eslintrc
- test/benchmark/index.js
- test/benchmark/property-access.js
- test/index.js
Closes #294
https://greenkeeper.io/
> chore(package): update rollup to version 0.41.1

- .gitignore
- .npmignore
- README.md
* Explain bower install in README
* Add .npmrc to ignore
> Explain bower install in README

- LICENSE.md
> Add LICENSE previously removed by accident

- .github/workflows/ci.yml
- .travis.yml
- README.md
- package.json
Remove Travis integration. Use GitHub actions instead.
> Moving to GitHub actions
