stampit-org/stampit

gruntfile.js, package.json, test/index.html
Simplifying development.
`grunt watch` to automate linting and build. And livereload to the unit test page to avoid F5 key strokes.
=> Add 'grunt watch' and live reload to the tests HTML.

README.md
@ericelliott, please review.
The bullet list of changes can be found in #71.
=> Readme v2 0

README.md, mixer.js, stampit.js, test/props-safety.js
@ericelliott @troutowicz @unstoppablecarl Please, review.
The main change is the object instantiation. See `function Factory()`.
Now all the references mixed into an object instance as is was before. But then the `props` are **safely** merged into the instance. "Safely" means that no refs data will be overriden, but props will be merged to the existing properties where possible. See the unit test of this PR.
In my opinion this is the very best approach for all existing user cases I have ever met so far.
=> Stamp function accept refs

package.json, stampit.js
Use closure variable instead of `this`. Stamp function should not depend on bound context. This improves code stability. Stamp behavior gets more predictable.
=> Detach `stamp.static()` and `stamp.compose()` from `this`

package.json
See https://github.com/ericelliott/prod-module-boilerplate/issues/18
When this is merged, PR to https://github.com/cdnjs/cdnjs/ should be made (with cdnjs-importer tool), so the existing stampit there is updated with new config. Then every new NPM release will be automatically published on CDNJS.
=> Support automatic releases to CDNJS

src/stampit.js, test/convert-constructor.js
See #128 
"static" properties from the old school constructors are copied to stamp as expected.
```js
function SomeClassLikeFunction() {}
SomeClassLikeFunction.staticProperty = function () {};
var stamp = stampit.convertConstructor(SomeClassLikeFunction);
stamp.staticProperty(); // ALL GOOD!
```
=> Implement "static" properties in the convertConstructor.

docs/API.md
I could be wrong, but I think this example was meant to also demonstrate the use of a local method.
=> Clear up `methods` example

README.md
I couldn't understand why the samples didn't want to work on my machine! After reading the API docs I realised they were wrong...
=> Fix README code samples by replacing `this` with `instance`

README.md
It's better to follow one way of doing things. The  `{instance}` in initializers confuses people when mentioned.
=> Change examples back to `this` for initializers

src/stampit.js
Creates a new object instance form the stamp.
Creates a new object instance from the stamp.
=> Fixed a typo changed "form" to "from"

docs/API.md
I'm sorry, I just caught it while I was reading the docs.
=> fix .props() example typo

.babelrc, .travis.yml, build/build.js, build/index.js, buildconfig.env.example, package.json, src/stampit.js
Here we go, I am not expecting it would be perfect for the first time, so please try it and tell me what should be different. For convenience I've packed dist folder so you can see produced result.
[dist.zip](https://github.com/stampit-org/stampit/files/291430/dist.zip)
To summarize what's different here. There are 3 bundles here without any external dependencies included. These are meant for a further bundling in a different environments.
**stampit.mjs** - full featured ES6 including modules, essentially same thing as source file
**stampit.js** - ES6 without modules to be used in current NodeJS 6
**stampit.es5.js** - ES5 with required polyfills included, mainly for browserify & webpack 1.x
Lastly there is also **stampit.full.js** (+ minified) which is also ES5 compatible, but with all …
=> Proper multi-environment build using rollup

build/index.js
I believe this is a reason of failed tests, because Node V5 & V6 are using NPM V3 with flat node_modules. The babel simply accepts list of names of plugins, you don't need to specify path there or even require that module, it will handle it properly.
I am also trying to keep `typeof-symbol` plugin there as I cannot imagine why it's failing. If you are right, I will put it back.
=> Fix build issues related to NPM 3 flat structure

README.md
Apparently documentation is not enough and finding those articles is not that easy. I am pushing this intentionally to master branch as that's what people will see when coming to repo.
=> Add link to medium articles

.gitignore, README.md, build/index.js, docs/API.md, src/compose.js, src/merge.js, src/stampit.js, test/import.js, test/is-composable.js, test/is-stamp.js, test/stampit-api.js
This allows `require('stampit/compose')`, `require('stampit/isStamp')`, `require('stampit/isComposable')`.
=> Build compose, isStamp, isComposable to the module root

.eslintrc, package.json, src/extract-functions.js, src/merge.js
I've replaced for loops using `++` operator with `reduce` which I would say is better in general.
Change for a rule "no-use-before-define" allows hoisting of functions which is necessary to pass with green lights :)
Updated airbnb since it was complaining about new version of eslint. Nothing for broken because of that.
=> Fix some lint issues and update airbnb

.npmignore
1. Remove files and folders we no longer have
2. Ignore all the dev "dot" files: babelrc, eslintrc, npmignore
3. Ignore `/coverage` (yeah, I published that folder to NPM)
4. Ignore `/build` as a dev file
5. Ignore `/src` because we have the `/dist` folder having the full `/src` in various formats
6. Ignore `/docs` because they are not recommended to be part of a distributable module
All the items here are discussable.
P.S. This reduces the packages by ~3 times (from 60K to 21K). Removing the docs only shrinks the npm tarball by 10K. Removing the coverage does roughly the same.
=> .npmignore - make the NPM package 3 time smaller

docs/API.md, src/compose.js, src/extract-functions.js, src/isComposable.js, src/isFunction.js, src/isObject.js, src/isPlainObject.js, src/isStamp.js, src/merge.js, src/stampit.js, src/standardise-descriptor.js, src/utils.js, test/composers.js, test/stampit-shortcuts.js
- Implement `composers` feature in a specs compatible way.
- Move all internal function to the utils.js for simplicity.
- Performance optimize object creation (create less closure objects)
- Performance optimize composition (create less closure objects)
=> Implement `composers` feature

src/is-function.js, src/is-object.js, src/isComposable.js, src/isStamp.js, src/utils.js
Rollup did not handle tree-shaking properly and exported everything to isStamp/isCompose functions. The files were huge instead of being small.
=> Rollup did not handle tree-shaking properly and exported everything

src/stampit.js, test/composers.js
Fixes:
* Composers array should have been deduplicated from the beginning. Not it is.
* The main stamp was missing in the `composables` argument when `stamp.compose()` syntax was used.
=> Composers fixes

README.md, src/utils.js
This removes the burden many people have. They don't need to polyfil anything now. With this PR Stampit core feature - **dependencelessness** (What a word!) is preserved. The resulting minified bundle increases by 100 bytes, the .min.gz bundle increases by 40 bytes. :)
=> IE11 and node.js 0.10 support by adding 100 more bytes to the bundle

README.md, package.json, src/stampit.js
After that all the stampit distros will have `stampit.version === "4.1.0"` property.
=> Add `stampit.version`.

package.json, test/tests.ts, types/index.d.ts
There is a "DefinitelyTyped" style `tests.ts` file which illustrate basic `stampit` usage under typescript.
=> Typescript support
